## Web scraping NBA Basketball Data from NBA reference

In [113]:
import urllib.request
    # pretty-print python data structures
from pprint import pprint
    # for parsing all the tables present
    # on the website
from html_table_parser.parser import HTMLTableParser
    # for converting the parsed data in a
    # pandas dataframe
import pandas as pd

In [112]:
# Library for opening url and creating
# requests
import urllib.request
    # pretty-print python data structures
from pprint import pprint
    # for parsing all the tables present
    # on the website
from html_table_parser.parser import HTMLTableParser
    # for converting the parsed data in a
    # pandas dataframe
import pandas as pd
import os
os.chdir('/Users/ruthvikpvs/Desktop/Projects/Nba and Aba Players')
def scraping_data(yes):
    import urllib.request
    # pretty-print python data structures
    from pprint import pprint
    # for parsing all the tables present
    # on the website
    from html_table_parser.parser import HTMLTableParser
    # for converting the parsed data in a
    # pandas dataframe
    import pandas as pd
    if yes =='TRUE':
        df = pd.DataFrame(columns = ['Player', 'From', 'To', 'Pos', 'Ht', 'Wt', 'Birth Date', 'Colleges']) # creates master dataframe
        letters ='abcdefghijklmnopqrstuvwxyz'
        for letter in letters:
            add_letter = str(letter) + '/'
            url = 'https://www.basketball-reference.com/players/' + add_letter
            req = urllib.request.Request(url=url)
            f = urllib.request.urlopen(req)
            f=f.read()
            xhtml =f.decode('utf-8')
            p = HTMLTableParser()

            # feeding the html contents in the
            # HTMLTableParser object
            p.feed(xhtml)
            d1=pd.DataFrame(p.tables[0])
            headers = d1.iloc[0]
            new_df  = pd.DataFrame(d1.values[1:], columns=headers)
            df=df.append(new_df)
        return df

## Division I,II and III data from NCAA College Men's Basketball website

In [102]:
import urllib.request
    # pretty-print python data structures
from pprint import pprint
    # for parsing all the tables present
    # on the website
from html_table_parser.parser import HTMLTableParser
    # for converting the parsed data in a
    # pandas dataframe
import pandas as pd

In [114]:
def college_players_div1():
    import urllib.request
    # pretty-print python data structures
    from pprint import pprint
    # for parsing all the tables present
    # on the website
    from html_table_parser.parser import HTMLTableParser
    # for converting the parsed data in a
    # pandas dataframe
    import pandas as pd
# DIVISION I PLAYERS
    list1 = ['p1','p2','p3','p4','p5','p6','p7','p8']

    data1 = pd.DataFrame(columns=['Rank', 'Name', 'Team', 'Cl', 'Height', 'Position', 'G', 'FGM', 'FT','PTS'])
    for i in list1:
        url = 'https://www.ncaa.com/stats/basketball-men/d1/current/individual/600' +'/'+ i
        req = urllib.request.Request(url=url)
        f = urllib.request.urlopen(req)
        f=f.read()
        xhtml =f.decode('utf-8')
        p = HTMLTableParser()

        # feeding the html contents in the
        # HTMLTableParser object
        p.feed(xhtml)
        d1=pd.DataFrame(p.tables[0])
        headers = d1.iloc[0]
        new_df1  = pd.DataFrame(d1.values[1:], columns=headers)
        data1=data1.append(new_df1)
    data1=data1.reset_index()
    data1.drop(columns=['index'],inplace=True,axis=1)
    for index,value in enumerate(data1.Rank):
        data1['Rank'][index]=index+1
    data1['division']='division1'
    return data1

In [115]:
def college_players_div2():
    
    list2 = ['p1','p2','p3','p4','p5','p6']
    data1 = college_players_div1()
    data2 = pd.DataFrame(columns=['Rank', 'Name', 'Team', 'Cl', 'Height', 'Position', 'G', 'FGM', 'FT','PTS'])
    for i in list2:
        url = 'https://www.ncaa.com/stats/basketball-men/d2/current/individual/600' +'/'+ i
        req = urllib.request.Request(url=url)
        f = urllib.request.urlopen(req)
        f=f.read()
        xhtml =f.decode('utf-8')
        p = HTMLTableParser()

        # feeding the html contents in the
        # HTMLTableParser object
        p.feed(xhtml)
        d1=pd.DataFrame(p.tables[0])
        headers = d1.iloc[0]
        new_df1  = pd.DataFrame(d1.values[1:], columns=headers)
        data2=data2.append(new_df1)
    data2=data2.reset_index()
    data2['division']='division2'
    data2.drop(columns=['index'],inplace=True,axis=1)
    for index,value in enumerate(data2.Rank):
        data2['Rank'][index]=index+1
    data1=data1.append(data2)
    return data1

In [116]:
def college_players_div3():
    
    list3 = ['p1','p2','p3','p4','p5']
    data1 = college_players_div2()
    data3 = pd.DataFrame(columns=['Rank', 'Name', 'Team', 'Cl', 'Height', 'Position', 'G', 'FGM', 'FT','PTS'])
    for i in list3:
        url = 'https://www.ncaa.com/stats/basketball-men/d3/current/individual/600' +'/'+ i
        req = urllib.request.Request(url=url)
        f = urllib.request.urlopen(req)
        f=f.read()
        xhtml =f.decode('utf-8')
        p = HTMLTableParser()

        # feeding the html contents in the
        # HTMLTableParser object
        p.feed(xhtml)
        d1=pd.DataFrame(p.tables[0])
        headers = d1.iloc[0]
        new_df1  = pd.DataFrame(d1.values[1:], columns=headers)
        data3=data3.append(new_df1)
    data3=data3.reset_index()
    data3['division']='division3'
    data3.drop(columns=['index'],inplace=True,axis=1)
    for index,value in enumerate(data3.Rank):
        data3['Rank'][index]=index+1
    data1=data1.append(data3)
    return data1

In [117]:
data = college_players_div3()

In [118]:
data

,Rank,Name,Team,Cl,Height,Position,G,FGM,FT,PTS,division
0,1,Isiaih Mosley,Missouri St.,Jr.,6-5,G,22,171,77,469,division1
1,2,Malachi Smith,Chattanooga,So.,6-4,G,21,156,97,452,division1
2,3,Darius McGhee,Liberty,Sr.,5-9,G,19,148,62,437,division1
3,4,Antonio Reeves,Illinois St.,Jr.,6-6,G,21,154,69,431,division1
4,5,Max Abmas,Oral Roberts,Jr.,6-0,G,19,142,69,430,division1
...,...,...,...,...,...,...,...,...,...,...,...
198,199,Pernell Ghee,Delaware Valley,Sr.,6-4,G,17,98,51,259,division3
199,200,Eli Harris,Roger Williams,Sr.,5-10,G,12,91,32,259,division3
200,201,Kyle Poerschke,Southwestern (TX),Sr.,-,G,16,94,50,259,division3
201,202,Alex Sikorski,Western New Eng.,Sr.,6-2,G,15,95,41,259,division3
202,203,Brandon Styers,Wooster,Sr.,6-3,G,15,94,48,259,division3